package models;
// Generated 02-feb-2017 13:48:33 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Enfermedad generated by hbm2java
 */
public class Enfermedad implements java.io.Serializable {

	private Integer idEnfermedad;
	private String nombre;
	private String sintomas;
	private Set pajaros = new HashSet(0);
	private Set tratamientos = new HashSet(0);

	public Enfermedad() {
	}

	public Enfermedad(String nombre, String sintomas, Set pajaros, Set tratamientos) {
		this.nombre = nombre;
		this.sintomas = sintomas;
		this.pajaros = pajaros;
		this.tratamientos = tratamientos;
	}

	public Integer getIdEnfermedad() {
		return this.idEnfermedad;
	}

	public void setIdEnfermedad(Integer idEnfermedad) {
		this.idEnfermedad = idEnfermedad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSintomas() {
		return this.sintomas;
	}

	public void setSintomas(String sintomas) {
		this.sintomas = sintomas;
	}

	public Set getPajaros() {
		return this.pajaros;
	}

	public void setPajaros(Set pajaros) {
		this.pajaros = pajaros;
	}

	public Set getTratamientos() {
		return this.tratamientos;
	}

	public void setTratamientos(Set tratamientos) {
		this.tratamientos = tratamientos;
	}

}
