package models;
// Generated 26-ene-2017 13:38:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento implements java.io.Serializable {

	private Integer idTratamiento;
	private Enfermedad enfermedad;
	private Medicamento medicamento;
	private Date fechaInicio;
	private Date fechaFin;

	public Tratamiento() {
	}

	public Tratamiento(Enfermedad enfermedad, Medicamento medicamento, Date fechaInicio, Date fechaFin) {
		this.enfermedad = enfermedad;
		this.medicamento = medicamento;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Integer getIdTratamiento() {
		return this.idTratamiento;
	}

	public void setIdTratamiento(Integer idTratamiento) {
		this.idTratamiento = idTratamiento;
	}

	public Enfermedad getEnfermedad() {
		return this.enfermedad;
	}

	public void setEnfermedad(Enfermedad enfermedad) {
		this.enfermedad = enfermedad;
	}

	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
